# version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: car_manual_db
    environment:
      POSTGRES_USER: car_manual_user
      POSTGRES_PASSWORD: car_manual_password
      POSTGRES_DB: car_manual_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U car_manual_user -d car_manual_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: